export default {

  API: {
    REQUEST_DATA: 'API_REQUEST_DATA',
    RECEIVE_DATA: 'API_RECEIVE_DATA'
  },
  PRODUCT: {
    RESET_STATE: 'PRODUCT_RESET_STATE',
    REQUEST_DATA: 'PRODUCT_LIST_REQUEST_DATA',
    SUCCESS_DATA: 'PRODUCT_LIST_SUCCESS_DATA',
    FAILED_DATA: 'PRODUCT_LIST_FAILED_DATA',

    REQUEST_CREATE: 'PRODUCT_CREATE_REQUEST_DATA',
    SUCCESS_CREATE: 'PRODUCT_CREATE_SUCCESS_DATA',
    ERROR_CREATE: 'PRODUCT_CREATE_ERROR_DATA',

    REQUEST_GET: 'PRODUCT_GET_REQUEST_DATA',
    SUCCESS_GET: 'PRODUCT_GET_SUCCESS_DATA',
    ERROR_GET: 'PRODUCT_GET_ERROR_DATA',

    REQUEST_UPDATE: 'PRODUCT_UPDATE_REQUEST_DATA',
    SUCCESS_UPDATE: 'PRODUCT_UPDATE_SUCCESS_DATA',
    ERROR_UPDATE: 'PRODUCT_UPDATE_ERROR_DATA',
    
    REQUEST_DELETE: 'PRODUCT_DELETE_REQUEST_DATA',
    REQUEST_DELETE_RESET: 'PRODUCT_DELETE_REQUEST_RESET_DATA',
    SUCCESS_DELETE: 'PRODUCT_DELETE_SUCCESS_DATA',
    ERROR_DELETE: 'PRODUCT_DELETE_ERROR_DATA',
  },
  CATEGORY:{
    REQUEST_DATA: 'CATEGORY_LIST_REQUEST_DATA',
    SUCCESS_DATA: 'CATEGORY_LIST_SUCCESS_DATA',
    FAILED_DATA: 'CATEGORY_LIST_FAILED_DATA',  
  }

};